name: Java CI - master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Cache maven repository
      uses: actions/cache@v1
      with:
        path: .m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install [deepinthink-buildstack/buildstack-maven-parent]
      run: |
        git clone https://github.com/deepinthink-buildstack/buildstack-maven-parent
        cd buildstack-maven-parent && ./mvnw "-Dmaven.repo.local=../.m2" -U -B install
    - name: Install [deepinthink-plasma/plasma-broker]
      run: |
        git clone https://github.com/deepinthink-plasma/plasma-broker
        cd plasma-broker && ./mvnw "-Dmaven.repo.local=../.m2" -U -B install
    - name: Build with Maven Wrapper
      run: ./mvnw "-Dmaven.repo.local=.m2" -U -B package
