name: Java CI - master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Cache maven repository
      uses: actions/cache@v1
      with:
        path: .m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Checkout [deepinthink-buildstack/buildstack-maven-parent]
      uses: actions/checkout@v2
      with:
        repository: deepinthink-buildstack/buildstack-maven-parent
        path: deepinthink-buildstack/buildstack-maven-parent
    - name: Install [deepinthink-buildstack/buildstack-maven-parent]
      run: |
        cd deepinthink-buildstack/buildstack-maven-parent
        ./mvnw "-Dmaven.repo.local=../../.m2" -U -B install

    - name: Checkout [deepinthink-plasma/plasma-proto]
      uses: actions/checkout@v2
      with:
        repository: deepinthink-plasma/plasma-proto
        path: deepinthink-plasma/plasma-proto

    - name: Checkout [deepinthink-plasma/plasma-common]
      uses: actions/checkout@v2
      with:
        repository: deepinthink-plasma/plasma-common
        path: deepinthink-plasma/plasma-common

    - name: Create Link [deepinthink-plasma/plasma-proto]
      run: |
        mkdir -p deepinthink-plasma/plasma-common/deepinthink-plasma
        cd deepinthink-plasma/plasma-common/deepinthink-plasma
        ln -s ../../plasma-proto plasma-proto

    - name: Install [deepinthink-plasma/plasma-common]
      run: |
        cd deepinthink-plasma/plasma-common
        ./mvnw "-Dmaven.repo.local=../../.m2" -U -B -P ci install

    - name: Checkout [deepinthink-plasma/plasma-broker]
      uses: actions/checkout@v2
      with:
        repository: deepinthink-plasma/plasma-broker
        path: deepinthink-plasma/plasma-broker
    - name: Install [deepinthink-plasma/plasma-broker]
      run: |
        cd deepinthink-plasma/plasma-broker
        ./mvnw "-Dmaven.repo.local=../../.m2" -U -B install

    - name: Checkout [deepinthink-plasma/plasma-login]
      uses: actions/checkout@v2
      with:
        repository: deepinthink-plasma/plasma-login
        path: deepinthink-plasma/plasma-login
    - name: Install [deepinthink-plasma/plasma-login]
      run: |
        cd deepinthink-plasma/plasma-login
        ./mvnw "-Dmaven.repo.local=../../.m2" -U -B install

    - name: Checkout [deepinthink-plasma/plasma-routing]
      uses: actions/checkout@v2
      with:
        repository: deepinthink-plasma/plasma-routing
        path: deepinthink-plasma/plasma-routing
    - name: Install [deepinthink-plasma/plasma-routing]
      run: |
        cd deepinthink-plasma/plasma-routing
        ./mvnw "-Dmaven.repo.local=../../.m2" -U -B install

    - name: Build with Maven Wrapper
      run: ./mvnw "-Dmaven.repo.local=.m2" -U -B package
